### ISSUE TITLE
Compile the markdown once when the article is saved

### ISSUE THREAD

**Issue by Oza94** [node-press/node-press#1]
Now the markdown is compiled when rendering the view. We should do it once when saving the model : 
- Add a `compiledContent` attribute on the model
- On save, if the markdown has changed, compile it and save it in `compiledContent`
- In the views, use `compiledContent` attribute

**Comment by sebay00** [comment]
Got it.

**Comment by Oza94** [comment]
Ok fixed.

**Comment by Oza94** [comment]
Can you please use `article.compliedContent` instead of `article.content` in views?

**Comment by Oza94** [comment]
Ok.
