### ISSUE TITLE
Add an article preview

### ISSUE THREAD

**Issue by Oza94** [node-press/node-press#9]
Add an article preview on the index page.

The preview string is extracted from the compiled html. Take the first 200 characters of the first `<p>` tag you encounter and save it into a `preview` attribute in the model.

You can use [xmldom](https://www.npmjs.com/package/xmldom) and [xpath](https://www.npmjs.com/package/xpath) to parse the html and extract the required content.

**Comment by sebay00** [comment]
I'll do it with RegExp.
